# Define the base image used for building the project
image: maven:3.8.4-jdk-11

# Define the stages for the pipeline
stages:
  - build
  - test

# Build stage
build:
  stage: build
  script:
    - mvn clean package -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

# Test stage
test:
  stage: test
  image: maven:3.8.4-jdk-11
  before_script:
#    - apt-get update
    #      - apt-get install -y libglib2.0-0 libnss3 libxcb1 google-chrome-stable
    #      - export CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    #      - curl -sS -o /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
    #      - unzip /tmp/chromedriver_linux64.zip -d /tmp
    #      - chmod +x /tmp/chromedriver
    #      - export PATH=$PATH:/tmp/
    #      - export CHROME_BIN=/usr/bin/google-chrome

    # Add BrowserStack settings
    - export BROWSERSTACK_USERNAME=anastasiya_Kc8GNg
    - export BROWSERSTACK_ACCESS_KEY=65KhVCyY92Emd7eMYXyy
    - export BROWSERSTACK_LOCAL=false
  script:
    # Add BrowserStack integration with Selenium
    - mvn test -Dbrowserstack.username=$BROWSERSTACK_USERNAME -Dbrowserstack.accesskey=$BROWSERSTACK_ACCESS_KEY
